import { random } from '.';

const adjectives = [
  'Excited',
  'Anxious',
  'Overweight',
  'Demonic',
  'Jumpy',
  'Misunderstood',
  'Squashed',
  'Gargantuan',
  'Broad',
  'Crooked',
  'Curved',
  'Deep',
  'Even',
  'Excited',
  'Anxious',
  'Overweight',
  'Demonic',
  'Jumpy',
  'Misunderstood',
  'Squashed',
  'Gargantuan',
  'Broad',
  'Crooked',
  'Curved',
  'Deep',
  'Even',
  'Flat',
  'Hilly',
  'Jagged',
  'Round',
  'Shallow',
  'Square',
  'Steep',
  'Straight',
  'Thick',
  'Thin',
  'Cooing',
  'Deafening',
  'Faint',
  'Harsh',
  'High-pitched',
  'Hissing',
  'Hushed',
  'Husky',
  'Loud',
  'Melodic',
  'Moaning',
  'Mute',
  'Noisy',
  'Purring',
  'Quiet',
  'Raspy',
  'Screeching',
  'Shrill',
  'Silent',
  'Soft',
  'Squeaky',
  'Squealing',
  'Thundering',
  'Voiceless',
  'Whispering',
];

const objects = [
  'Taco',
  'Operating System',
  'Sphere',
  'Watermelon',
  'Cheeseburger',
  'Apple Pie',
  'Spider',
  'Dragon',
  'Remote Control',
  'Soda',
  'Barbie Doll',
  'Watch',
  'Purple Pen',
  'Dollar Bill',
  'Stuffed Animal',
  'Hair Clip',
  'Sunglasses',
  'T-shirt',
  'Purse',
  'Towel',
  'Hat',
  'Camera',
  'Hand Sanitizer Bottle',
  'Photo',
  'Dog Bone',
  'Hair Brush',
  'Birthday Card',
];

export default function getDisplayName(): string {
  const adj = adjectives[random(0, adjectives.length)];
  const obj = objects[random(0, objects.length)];
  return `${adj} ${obj}`;
}
